# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: 'tiny-money-frontend'

- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    customCommand: 'test'
    workingDir: 'tiny-money-frontend'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    customCommand: 'run build'
    workingDir: 'tiny-money-frontend'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'website'
    pathtoPublish: '$(System.DefaultWorkingDirectory)/tiny-money-frontend/dist'
