name: Backend Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - "backend"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: backend
      run: docker build . --file MW.TinyMoney.Api\Dockerfile --tag mw-tiny-money-api:$(date +%s)
