name: CI Build
on:
  push:
    branches: [ master ]
    paths:
      - tinymoney-frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
        working-directory: tinymoney-frontend